import streamlit as st
from dotenv import load_dotenv
import json

load_dotenv()

from agent import get_agent
from utils import create_ics_file, create_pdf_file, parse_markdown_itinerary
import datetime

st.set_page_config(page_title="Local Discovery AI", page_icon="🗺️", layout="wide")

st.title("🗺️ Local Discovery AI")
st.markdown("Your personalized agent for discovering the best places around you.")

# Sidebar for Preferences
with st.sidebar:
    st.header("Preferences")
    
    # 1. Cuisines (for Restaurants)
    selected_cuisines = st.multiselect(
        "Select Cuisines",
        ["Italian", "Chinese", "Indian", "Mexican", "Continental", "Cafe"],
        default=["Indian"]
    )
    
    # 2. Activities (Non-Food)
    selected_activities = st.multiselect(
        "Select Activities",
        ["Parks", "Museums", "Shopping", "Movies", "Zoo"],
        default=["Shopping"]
    )
    
    st.divider()
    
    # Popular Areas in Bangalore
    areas = {
        "Koramangala": "12.9352,77.6245",
        "Indiranagar": "12.9719,77.6412",
        "MG Road": "12.9756,77.6066",
        "Whitefield": "12.9698,77.7500",
        "Jayanagar": "12.9308,77.5838",
        "Malleshwaram": "13.0031,77.5643",
        "HSR Layout": "12.9121,77.6446"
    }
    
    selected_area = st.selectbox("Choose an Area", list(areas.keys()))
    location_input = areas[selected_area]
    st.caption(f"Coordinates: {location_input}")
    
    st.divider()
    if st.button("Reset Agent Memory 🧹"):
        st.session_state.clear()
        st.rerun()

if st.button("Plan My Day 🚀", type="primary"):
    with st.spinner("Agent is working..."):
        agent = get_agent()
        
        # Combine interests for the agent
        all_interests = [f"{c} Restaurant" for c in selected_cuisines] + selected_activities
        
        # Construct the prompt
        prompt = f"""
        Plan a perfect outing for me!
        - **Location**: {selected_area} (Coordinates: {location_input})
        - **Interests**: {", ".join(all_interests)}
        
        Please find relevant places, enrich them with details, and create a mini-itinerary.
        """
        
        # Run the agent
        response = agent.run(prompt)
        st.session_state['itinerary'] = response.content

# Display Itinerary if available
if 'itinerary' in st.session_state:
    st.markdown(st.session_state['itinerary'])
    
    # Parse for Export
    try:
        items, extracted_summary = parse_markdown_itinerary(st.session_state['itinerary'])
        summary = extracted_summary if extracted_summary else "Your custom itinerary generated by Local Discovery AI."
        
        if items:
            # Export Options
            st.divider()
            col1, col2 = st.columns(2)
            with col1:
                st.download_button(
                    label="Add to Calendar 📅",
                    data=create_ics_file(items),
                    file_name="itinerary.ics",
                    mime="text/calendar"
                )
            with col2:
                st.download_button(
                    label="Download PDF 📄",
                    data=create_pdf_file(items, summary),
                    file_name="itinerary.pdf",
                    mime="application/pdf"
                )
        else:
            st.warning("Could not extract structured data for export. Please try again.")
            
    except Exception as e:
        st.error(f"An error occurred during export preparation: {e}")
